name: Testeo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: |
          pytest tests/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check for package.json
        id: check_package_json
        run: |
          if [ -f "package.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for package-lock.json
        id: check_package_lock
        run: |
          if [ -f "package-lock.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Node.js dependencies
        if: steps.check_package_json.outputs.exists == 'true'
        run: |
          if [ "${{ steps.check_package_lock.outputs.exists }}" == "true" ]; then
            npm ci
          else
            npm install
          fi

      - name: Run Node.js tests
        if: steps.check_package_json.outputs.exists == 'true'
        run: npm test